before_script:
  - . ~/.nvm/nvm.sh
  - nvm use 6.9.1
  - npm install -g gulp bower

cache:
  paths:
    - node_modules/
    - bower_components

stages:
  - deploy

deploy_master:
  stage: deploy
  script:
    - npm install
    - bower install
    - NODE_ENV=production gulp dist --backend https://backend.histocito.net --node https://backend.histocito.net:3001
    - rsync -rlDv --delete dist /software/histocito/frontend
  environment:
    name: master
    url: https://app.histocito.net
  only:
  - master
  tags:
  - histocito-frontend

deploy_desarrollo:
  stage: deploy
  script:
    - npm install
    - bower install
    - NODE_ENV=production gulp dist --backend http://pruebas.ciriscr.com:17001 --node http://pruebas.ciriscr.com:3001
    - rsync -rlDv --delete dist /software/histocito/frontend
  environment:
    name: desarrollo
    url: http://pruebas.ciriscr.com:3000
  only:
  - desarrollo
  tags:
  - pruebas
